### ISSUE TITLE
Environment Config file

### ISSUE THREAD

**Issue by lucasliunju** [junkangwu/alpha-DPO#1]
Hi,

Thanks for your great work. May I ask the config file of the training environment, such as requirements.txt file.

Thank you!

**Comment by junkangwu** [comment]
Thank you for your interest. 
The requirements.txt file has been added to the project. If you have any questions or issues, please don't hesitate to contact me.

**Comment by lucasliunju** [comment]
Hi, thanks for your reply. 

I try to use `alpaca_eval evaluate_from_model   --model_configs` to evaluate the trained model and I find that will need to use openai API. I initially topped up my account with $10, but this was quickly depleted after only a few evaluations. Do you have some suggestions on that because I don't have enough funding for that.

**Comment by junkangwu** [comment]
You can try two approaches: 1) Switch to more cost-effective base models like Qwen, ChatGLM, etc. 2) Use third-party OpenAI API providers, which may offer discounts. Both options can help reduce evaluation costs.

**Comment by lucasliunju** [comment]
Thank you very much! May I ask how to use this code to run vanilla DPO.

**Comment by junkangwu** [comment]
You need to modify `loss_type=sigmoid`, and both learning rate and beta need to be re-tuned. Generally speaking, set beta=0.01 and learning rate=5e-7.

**Comment by lucasliunju** [comment]
Thank you very much for your help!

**Comment by lucasliunju** [comment]
Hi, I still have a question about the environment. I try to install `trl==0.8.6` and `alignment-handbook==0.4.0.dev0`. But it occurs the error: 

```
  File "alignment-handbook/src/alignment/configs.py", line 240, in <module>
    class SFTConfig(trl.SFTConfig):
  File "/alpha-dpo/lib/python3.10/site-packages/trl/import_utils.py", line 169, in __getattr__
    raise AttributeError(f"module {self.__name__} has no attribute {name}")
AttributeError: module trl has no attribute SFTConfig. Did you mean: 'CPOConfig'?

```

Do you encounter this error and I think this is because the alignment-handbook has been updated multiple times although the version is still `0.4.0.dev0` 

It could be better if you could share your alignment-handbook folder. 

Thank you!

**Comment by junkangwu** [comment]
Is this error occurring after installation when executing the program? I haven't encountered a similar issue on my end. Perhaps you could try upgrading to a newer version of trl and see if that helps?

**Comment by lucasliunju** [comment]
Hi @junkangwu 

Thanks for your reply. I try to use a old version of alignment-handbook (about 5 month ago) and it can run now. 

By the way, the evaluation on alpacaeval is so expensive (each evaluation takes about 7 dollars) and I try to use llama3 to solve it.

**Comment by junkangwu** [comment]
All our environments are consistent with [SimPO](https://github.com/princeton-nlp/SimPO). At that time, I used the latest version of alignment-handbook. I suspect the update to alignment-handbook caused compatibility issues with trl. Thanks for pointing this out; we'll try to verify this environment alignment issue again.

AlpacaEval is indeed an expensive evaluation method. Without funding, finding an alternative is certainly an option.

**Comment by lucasliunju** [comment]
Hi @junkangwu 

sorry to trouble you again. I have finished the training with this codebase but I find I cannot evaluate it with alpacaeval. The evaluation stop on: 

```
libi40iw-i40iw_ualloc_context: failed to allocate context for device.
libi40iw-i40iw_ualloc_context: failed to allocate context for device.
INFO 10-24 19:53:20 model_runner.py:104] Loading model weights took 14.9595 GB
INFO 10-24 19:53:21 gpu_executor.py:94] # GPU blocks: 27780, # CPU blocks: 2048
INFO 10-24 19:53:22 model_runner.py:791] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
INFO 10-24 19:53:22 model_runner.py:795] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
INFO 10-24 19:53:25 model_runner.py:867] Graph capturing finished in 3 secs.

Processed prompts:   0%|                                                                                                                                                                                                  | 0/64 [00:00<?, ?it/s]
```

I try to wait 10 mins and no any update, the Processed prompts is still 0%. But I use the official simpo checkpoint can successfully run and evaluate the simpo model. 

this is my checkpoint folder:

![image](https://github.com/user-attachments/assets/d9a9bc44-973d-4646-98ab-48e1beb0b2a6)

**Comment by junkangwu** [comment]
Which model base and dataset are you running? Can you check wandb to see if the training process is normal?

**Comment by lucasliunju** [comment]
I am using llama3-8b-instruct as pre-trained model and try to train vanilla dpo. The is my result from wandb: 

![image](https://github.com/user-attachments/assets/1ac9e97e-8c59-493c-bf50-31e76a997e8a)

![image](https://github.com/user-attachments/assets/ed0941eb-a5b4-4e8f-bca0-ea6cbf053cc8)

**Comment by junkangwu** [comment]
Here are my model parameters for vanilla dpo that may need to be double-checked. My parameter settings are:

ln: False
trainer_type: dpo
loss_type: sigmoid
learning_rate: 1e-6
beta: 1e-2

I suspect your `ln` setting might be incorrect. Here, `ln` represents whether to use length normalization. If set to true, beta should be set to 10.0; if false, it should be set to 0.01.

**Comment by lucasliunju** [comment]
Thanks for your reply! That will help me a lot. I will have a try. By the way, may I ask whether you can share the wandb file and I can check my training results.

**Comment by junkangwu** [comment]
Here is the result on DPO with llama3-8b-instruct (llama-3-8b-instruct-V1-simpo-0910-dpo-sigmoid-ln-False-beta-0.01-gamma-0.0-raito-0.0-lr-1e-6)
![image](https://github.com/user-attachments/assets/17258aa4-672f-410f-8d9c-44c2f254b538)
![image](https://github.com/user-attachments/assets/f2d68a2c-b29d-48c4-b973-b2460cf499ba)
