### ISSUE TITLE
Confusion about Theorem 3.1 and Gradient analysis

### ISSUE THREAD

**Issue by AIR-hl** [junkangwu/alpha-DPO#5]
Hi! Thanks for ur noval work, first, i have some quesiton about _theorem 3.1_:

1. According to common understanding, for a uniform distribution $U(\cdot|x)$, $U(y_1|x)$ and $U(y_2|x)$ should be equal, so $\gamma=0$ in this case. 

2. Otherwise, in the formulation of _theorem 3.1,_ , the uniform distribution assumption is based on vocabulary, it means $\gamma$ cant be a fixed value since the length difference in different pair data: 
$$\gamma = \beta \left[ \sum_{i=1}^{|y_1|} \log \frac{1}{|\mathcal{V}|} - \sum_{i=1}^{|y_2|} \log \frac{1}{|\mathcal{V}|} \right]$$

Quesiton about gradient：

I derive the gradient for $\alpha$-DPO in the same way as in DPO. The weight term is as follows, assuming there are no errors:
$\sigma\left(\frac{\beta}{|y_l|}\log\pi_\theta(y_l|x) - \frac{\beta}{|y_w|}\log\pi_\theta(y_w|x) + \gamma + \alpha M(x,y_w,y_l)\right)$. 

According to the DPO paper, when $(r_l - r_w)$ increases, the weight also increases to penalize the data and promote more significant updates. However, in this work, when the policy effectively allocates rewards for the pair ($y_w \gg y_l$), $M(x, y_w, y_l)$ still tries to increase the weight, which seems somewhat counterintuitive. 

Please forgive me if I missed anything. Thank u again and wish u all the best!

**Comment by junkangwu** [comment]
Thanks for your interest!

1. **We first want to jusitfy that the uniform distribution assumption is proper, and the uniform distribution does not lead to $\gamma = 0$.** The uniform distribution assumption on a LLM describes this model as not having any alignment w.r.t human preference. It is commonly happening in the LLM without enough high equality instruction tuning. The positive/negative samples are generated via reject sampling procedures on LLM and the corresponding distributions are different.

Let's revisit the acquisition method for these samples (e.g., using princeton-nlp/llama3-ultrafeedback dataset): For each prompt $x$, we generate 5 responses using the SFT model with a sampling temperature of 0.8. We then score these responses with llm-blender/PairRM and select the highest-scoring one as $y_w$ and the lowest-scoring one as $y_l$.

For the highest-scoring sample $y_w$, it follows a new conditional distribution:

$$\pi(y \mid x, \text{score}(y) = \max({\text{score}(y_1), \ldots, \text{score}(y_5)}))\approx\pi(win|x),$$

where the last part uses the assumption that for a given x the generative model has a uniform chance to generate all possible y. Similarly, for the lowest-scoring sample $y_l$, it follows:

$$\pi(y \mid x, \text{score}(y) = \min({\text{score}(y_1), \ldots, \text{score}(y_5)}))\approx \pi(lose|x)$$

Each response is generated from the same conditional distribution $\pi_{\text{SFT}}$, implying the same distribution during generation. However, by scoring and selecting using llm-blender/PairRM, there is an inherent selection bias. In the above setting, the $\gamma$ value is $\gamma \approx \log \pi (win|x) - \log \pi(lose|x)$.

2. **Mitigating the impact of label flipping noise.** As $(r_l - r_w)$ increases, the weight also increases, leading to more significant updates. However, this is not the desired effect. For example, when label flipping occurs and $y_w$ and $y_l$ are swapped, an increase in $(r_l - r_w)$ will amplify the impact of noise. There are many other articles that have similarly pointed out this issue (cDPO[1], rDPO[2]). On the contrary, $\alpha$-DPO can mitigate the impact of label flipping noise, which is also its advantage.

[1] Rafailov, R., Sharma, A., Mitchell, E., Manning, C. D., Ermon, S., & Finn, C. (2023). A note on DPO with noisy preferences and relationship to IPO. https://ericmitchell.ai/cdpo.pdf.

[2] Chowdhury, S. R., Kini, A., & Natarajan, N. (2024). Provably robust DPO: Aligning language models with noisy feedback. In ICML 2024.

Please let me know if there’s anything I missed. Thank you again, and best wishes!

**Comment by AIR-hl** [comment]
Thank you for your reply! I got ur thoughts now. But I have two more points to clarify here.

First, it seems that the explanation of the uniform distribution is based on an online dataset, more generally, responses are sampled from different policy models and annatated by llm judge (e.g. GPT-4)

Second, nowadays, preference labels annotated by advanced reward models can achieve high consistency with human, and allocating a high weight for high confidence pair data is a risk of overfitting, as mentioned in the IPO.

Anyway, i think this is a valuable work!
